# Generated by Django 4.2.29 on 2026-03-20 23:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_name', models.CharField(max_length=120)),
                ('bottle_id', models.SlugField(max_length=64, unique=True)),
                ('total_volume_liters', models.DecimalField(decimal_places=3, max_digits=6)),
                ('bottle_height_reference', models.PositiveIntegerField(help_text='Reference bottle height in pixels for calibration.')),
                ('height_to_volume_ratio', models.DecimalField(decimal_places=6, help_text='Liters per pixel of height based on calibration.', max_digits=10)),
                ('cup_conversion_ratio', models.DecimalField(decimal_places=3, default=0.25, help_text='Liters per cup. Default: 0.250', max_digits=6)),
                ('shape_type', models.CharField(choices=[('cylinder', 'Cylinder'), ('rectangular', 'Rectangular'), ('curved', 'Curved')], default='cylinder', max_length=32)),
                ('calibration_points', models.JSONField(default=list, help_text='List of calibration points. Example: [{pixel: 1200, liters: 5.0}].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('device_metadata', models.JSONField(blank=True, default=dict)),
                ('lighting_conditions', models.CharField(blank=True, max_length=120)),
                ('camera_type', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_sessions', to='oil.bottlespecification')),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='scans/original/')),
                ('processed_image', models.ImageField(blank=True, upload_to='scans/processed/')),
                ('oil_height_pixels', models.FloatField(blank=True, null=True)),
                ('bottle_height_pixels', models.FloatField(blank=True, null=True)),
                ('oil_ratio', models.FloatField(blank=True, null=True)),
                ('remaining_volume_liters', models.FloatField(blank=True, null=True)),
                ('consumed_volume_liters', models.FloatField(blank=True, null=True)),
                ('remaining_cups', models.FloatField(blank=True, null=True)),
                ('consumed_cups', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='oil.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='CupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_cups', models.FloatField()),
                ('target_image', models.ImageField(blank=True, upload_to='scans/targets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_targets', to='oil.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='BottleReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_bottles/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='oil.bottlespecification')),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_cups', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='oil.scansession')),
            ],
        ),
    ]
