# Generated by Django 4.2.29 on 2026-04-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/')),
                ('actual_oil_percentage', models.FloatField(help_text='Actual oil level 0-100 as reported by the tester')),
                ('lighting', models.CharField(choices=[('daylight', 'Natural Daylight'), ('fluorescent', 'Fluorescent/Indoor'), ('dim', 'Dim/Low Light'), ('direct_sun', 'Direct Sunlight'), ('mixed', 'Mixed Lighting')], default='daylight', max_length=32)),
                ('environment', models.CharField(choices=[('kitchen', 'Kitchen'), ('store', 'Store/Shelf'), ('outdoor', 'Outdoor'), ('office', 'Office'), ('other', 'Other')], default='kitchen', max_length=32)),
                ('camera_info', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Tester name or ID', max_length=120)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin for use in training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='oil.bottlespecification')),
            ],
        ),
    ]
