# Generated by Django 4.2.29 on 2026-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0002_trainingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanimage',
            name='bottle_bbox',
            field=models.JSONField(blank=True, help_text='Bottle bounding box: {x, y, w, h, image_w, image_h}', null=True),
        ),
    ]
