# Generated by Django 4.2.29 on 2026-04-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0004_seed_bottles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g. 'عافية زيت ذرة نقي 1.5 لتر')", max_length=200)),
                ('name_en', models.CharField(blank=True, help_text='English product name', max_length=200)),
                ('product_type', models.CharField(choices=[('corn', 'Corn Oil / زيت ذرة'), ('sunflower', 'Sunflower Oil / زيت عباد الشمس'), ('olive', 'Olive Oil / زيت زيتون'), ('blend', 'Blended Oil / زيت مخلوط'), ('canola', 'Canola Oil / زيت كانولا')], default='corn', max_length=32)),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume in ml (e.g. 1500)')),
                ('barcode', models.CharField(blank=True, help_text='EAN/UPC barcode number', max_length=64)),
                ('image', models.ImageField(blank=True, help_text='Reference photo of the label', upload_to='labels/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle', models.ForeignKey(blank=True, help_text='Linked bottle specification for oil level detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='oil.bottlespecification')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The full QR code content (URL or text scanned from the bottle)', max_length=500, unique=True)),
                ('batch_number', models.CharField(blank=True, help_text='Production batch number', max_length=64)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('factory_code', models.CharField(blank=True, help_text='Factory/plant code', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code is still valid')),
                ('scan_count', models.PositiveIntegerField(default=0, help_text='Number of times this QR was scanned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(help_text='The label/product this QR code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='oil.label')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.CharField(help_text='QR code content that was scanned', max_length=500)),
                ('scanned_label_name', models.CharField(blank=True, help_text='What label the user reported/detected on the bottle', max_length=200)),
                ('result', models.CharField(choices=[('match', 'Match ✓'), ('mismatch', 'Mismatch ✗'), ('qr_not_found', 'QR Not Found')], max_length=16)),
                ('bottle_image', models.ImageField(blank=True, upload_to='verifications/')),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_label', models.ForeignKey(blank=True, help_text='The label the QR code should match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='oil.label')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='oil.qrcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
