# Generated by Django 4.2.29 on 2026-04-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0005_label_qrcode_verificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='oil_references/')),
                ('level_percentage', models.FloatField(help_text='Oil level as a percentage (0-100).')),
                ('version', models.PositiveIntegerField(default=1, help_text='Bumped on every re-extraction — enables rollback.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active references are used at scan time.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('brightness_profile', models.JSONField(blank=True, null=True)),
                ('histogram', models.JSONField(blank=True, null=True)),
                ('golden_profile', models.JSONField(blank=True, null=True)),
                ('golden_amount', models.FloatField(blank=True, null=True)),
                ('normalized_cache_path', models.CharField(blank=True, max_length=500)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle', models.ForeignKey(blank=True, help_text='Bottle spec this reference belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_references', to='oil.bottlespecification')),
            ],
            options={
                'ordering': ['-level_percentage'],
                'indexes': [models.Index(fields=['is_active', 'level_percentage'], name='oil_oilrefe_is_acti_18d15a_idx')],
            },
        ),
    ]
